# Generated by Django 4.2.4 on 2023-08-26 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descriptios',
            new_name='description',
        ),
    ]
